# Copy to secrets.properties and fill in the values
# These values fill the ${...} placeholders in application.properties
DB_URL=
DB_USERNAME=
DB_PASSWORD=

# For a local DB, use these instead of the three lines above
#DB_URL=
#DB_USERNAME=
#DB_PASSWORD=

KHOA_KEY=
KWARE_KEY=
TRITON_URL=
